<?php
// $Id: sts_panelsargsubs.module,v 1.1 2009/08/17 22:07:14 that0n3guy Exp $

/*
 * @file
 *
 */


/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * sts_panelsargsubs/panels are used.
 */
function sts_panelsargsubs_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

